name: Deploy MultiK8s
on:
  push:
    branches:
      - master

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t sayandafadar/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true sayandafadar/react-test npm test

      - name: Set Identity Provider
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: "projects/226388803917/locations/global/workloadIdentityPools/github/providers/my-provider"
          service_account: "gh-deployer@multi-k8s-446306.iam.gserviceaccount.com"

      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: multi-k8s-446306

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-cluster
          location: asia-south2-a

      - name: Build
        run: |-
          docker build -t sayandafadar/multi-client-k8s-gh:latest -t sayandafadar/multi-client-k8s-gh:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t sayandafadar/multi-server-k8s-pgfix-gh:latest -t sayandafadar/multi-server-k8s-pgfix-gh:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t sayandafadar/multi-worker-k8s-gh:latest -t sayandafadar/multi-worker-k8s-gh:${{ env.SHA }} -f ./worker/Dockerfile ./worker

      - name: Push
        run: |-
          docker push sayandafadar/multi-client-k8s-gh:latest
          docker push sayandafadar/multi-server-k8s-pgfix-gh:latest
          docker push sayandafadar/multi-worker-k8s-gh:latest

          docker push sayandafadar/multi-client-k8s-gh:${{ env.SHA }}
          docker push sayandafadar/multi-server-k8s-pgfix-gh:${{ env.SHA }}
          docker push sayandafadar/multi-worker-k8s-gh:${{ env.SHA }}

      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=sayandafadar/multi-server-k8s-pgfix-gh:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=sayandafadar/multi-client-k8s-gh:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=sayandafadar/multi-worker-k8s-gh:${{ env.SHA }}
